### ISSUE TITLE
[bug] title error

### ISSUE THREAD

**Issue by TinsFox** [3lang3/rcdoc#3]
<img width="1956" alt="image" src="https://user-images.githubusercontent.com/33956589/166860698-ce74250d-9a99-4549-bb51-bb6e3bd2e0dc.png">

页签的title跟实际浏览组件不一致
[recurrent link](https://react-vant.3lang.dev/components/picker#%E5%9C%A8%E6%A1%8C%E9%9D%A2%E7%AB%AF%E6%97%A0%E6%B3%95%E6%93%8D%E4%BD%9C%E7%BB%84%E4%BB%B6)

**Comment by 3lang3** [comment]
收到
